/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedGeneratorRouteImport } from './routes/_authenticated/generator'
import { Route as AuthenticatedVaultIndexRouteImport } from './routes/_authenticated/vault.index'
import { Route as AuthenticatedVaultItemIdRouteImport } from './routes/_authenticated/vault.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGeneratorRoute = AuthenticatedGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultIndexRoute = AuthenticatedVaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultItemIdRoute =
  AuthenticatedVaultItemIdRouteImport.update({
    id: '/vault/$itemId',
    path: '/vault/$itemId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/plans': typeof PlansRoute
  '/reset-password': typeof ResetPasswordRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/vault/$itemId': typeof AuthenticatedVaultItemIdRoute
  '/vault/': typeof AuthenticatedVaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/plans': typeof PlansRoute
  '/reset-password': typeof ResetPasswordRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/vault/$itemId': typeof AuthenticatedVaultItemIdRoute
  '/vault': typeof AuthenticatedVaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/plans': typeof PlansRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/generator': typeof AuthenticatedGeneratorRoute
  '/_authenticated/vault/$itemId': typeof AuthenticatedVaultItemIdRoute
  '/_authenticated/vault/': typeof AuthenticatedVaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/plans'
    | '/reset-password'
    | '/generator'
    | '/vault/$itemId'
    | '/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/plans'
    | '/reset-password'
    | '/generator'
    | '/vault/$itemId'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/plans'
    | '/reset-password'
    | '/_authenticated/generator'
    | '/_authenticated/vault/$itemId'
    | '/_authenticated/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlansRoute: typeof PlansRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/generator': {
      id: '/_authenticated/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AuthenticatedGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault/': {
      id: '/_authenticated/vault/'
      path: '/vault'
      fullPath: '/vault/'
      preLoaderRoute: typeof AuthenticatedVaultIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault/$itemId': {
      id: '/_authenticated/vault/$itemId'
      path: '/vault/$itemId'
      fullPath: '/vault/$itemId'
      preLoaderRoute: typeof AuthenticatedVaultItemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGeneratorRoute: typeof AuthenticatedGeneratorRoute
  AuthenticatedVaultItemIdRoute: typeof AuthenticatedVaultItemIdRoute
  AuthenticatedVaultIndexRoute: typeof AuthenticatedVaultIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGeneratorRoute: AuthenticatedGeneratorRoute,
  AuthenticatedVaultItemIdRoute: AuthenticatedVaultItemIdRoute,
  AuthenticatedVaultIndexRoute: AuthenticatedVaultIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PlansRoute: PlansRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
